linters:
  enable:
    - revive
    - unconvert
    - dupl
    - goconst
    - gofmt
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gosec
linters-settings:
  misspell:
    locale: US
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false
  exclude:
    # gosec: Duplicated errcheck checks
    - G104
