name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.23', '1.24' ]

    name: Go ${{ matrix.go }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Send coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt
        flag-name: Go-${{ matrix.go }}
        parallel: true

  check-coverage:
    name: Check coverage
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
